Fix build failure when switching between build variants
When switching from the eng to the userdebug build variant, the init
binary compilation returns error ar linking stage:
.../obj/EXECUTABLES/init_intermediates/init.o: In function `bootchart_init_action':
system/core/init/init.c:729: undefined reference to `bootchart_init'
.../obj/EXECUTABLES/init_intermediates/init.o: In function `main':
system/core/init/init.c:881: undefined reference to `bootchart_step'
system/core/init/init.c:882: undefined reference to `bootchart_finish'
collect2: ld returned 1 exit status
make: *** [.../obj/EXECUTABLES/init_intermediates/LINKED/init] Error 1

Issue: ANDROID-1757
Change-Id: Ide50286e190ffeb75ec56bdfa2f5c612e0ae2392
Signed-off-by: Alin Dobre <alin.m.dobre@intel.com>